config/routes.rb
EnergySaving::Application.routes.draw do
  root 'homes#index'
  resources :calculates

  resources :messages

  resources :customers

  resources :salutations

  devise_for :teams
  resources :manufacturers

  resources :countries

  resources :materials

  

  resources :windows

  resources :manufacturers
    resources :abouts
     resources :homes 
     resources :calculates
     resources :partners
     resources :contacts 

  

    get '/img/:name', to: redirect {|params, req| "/assets/#{params[:name]}.#{params[:format]}"}
    get '/images/:name', to: redirect {|params, req| "/assets/#{params[:name]}.#{params[:format]}"}
    get '/stylesheets/:name', to: redirect {|params, req| "/css/#{params[:name]}.#{params[:format]}"}
    get '/javascripts/:name', to: redirect {|params, req| "/js/#{params[:name]}.#{params[:format]}"}

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/calculate.rb
class Calculate < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :salutation
  
  def fullName
    fullName = firstName + " " + lastName
  end
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :customer
end

app/models/partner.rb
class Partner < ActiveRecord::Base
end

app/models/salutation.rb
class Salutation < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/window.rb
class Window < ActiveRecord::Base
  belongs_to :manufacturer
  belongs_to :materials
end

app/controllers/salutations_controller.rb
class SalutationsController < ApplicationController
  before_action :set_salutation, only: [:show, :edit, :update, :destroy]

  # GET /salutations
  # GET /salutations.json
  def index
    @salutations = Salutation.all
  end

  # GET /salutations/1
  # GET /salutations/1.json
  def show
  end

  # GET /salutations/new
  def new
    @salutation = Salutation.new
  end

  # GET /salutations/1/edit
  def edit
  end

  # POST /salutations
  # POST /salutations.json
  def create
    @salutation = Salutation.new(salutation_params)

    respond_to do |format|
      if @salutation.save
        format.html { redirect_to @salutation, notice: 'Salutation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @salutation }
      else
        format.html { render action: 'new' }
        format.json { render json: @salutation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salutations/1
  # PATCH/PUT /salutations/1.json
  def update
    respond_to do |format|
      if @salutation.update(salutation_params)
        format.html { redirect_to @salutation, notice: 'Salutation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @salutation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salutations/1
  # DELETE /salutations/1.json
  def destroy
    @salutation.destroy
    respond_to do |format|
      format.html { redirect_to salutations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salutation
      @salutation = Salutation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salutation_params
      params.require(:salutation).permit(:salutation)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/calculate_helper.rb
module CalculateHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/salutations_helper.rb
module SalutationsHelper
end

app/helpers/windows_helper.rb
module WindowsHelper
end

app/views/salutations/_form.html.erb
<%= form_for(@salutation) do |f| %>
  <% if @salutation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salutation.errors.count, "error") %> prohibited this salutation from being saved:</h2>

      <ul>
      <% @salutation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :salutation %><br>
    <%= f.text_field :salutation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salutations/edit.html.erb
<h1>Editing salutation</h1>

<%= render 'form' %>

<%= link_to 'Show', @salutation %> |
<%= link_to 'Back', salutations_path %>

app/views/salutations/index.html.erb
<h1>Listing salutations</h1>

<table>
  <thead>
    <tr>
      <th>Salutation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @salutations.each do |salutation| %>
      <tr>
        <td><%= salutation.salutation %></td>
        <td><%= link_to 'Show', salutation %></td>
        <td><%= link_to 'Edit', edit_salutation_path(salutation) %></td>
        <td><%= link_to 'Destroy', salutation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salutation', new_salutation_path %>

app/views/salutations/new.html.erb
<h1>New salutation</h1>

<%= render 'form' %>

<%= link_to 'Back', salutations_path %>

app/views/salutations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Salutation:</strong>
  <%= @salutation.salutation %>
</p>

<%= link_to 'Edit', edit_salutation_path(@salutation) %> |
<%= link_to 'Back', salutations_path %>