config/routes.rb
EnergySaving::Application.routes.draw do
  root 'homes#index'
  resources :calculates

  resources :messages

  resources :customers

  resources :salutations

  devise_for :teams
  resources :manufacturers

  resources :countries

  resources :materials

  

  resources :windows

  resources :manufacturers
    resources :abouts
     resources :homes 
     resources :calculates
     resources :partners
     resources :contacts 

  

    get '/img/:name', to: redirect {|params, req| "/assets/#{params[:name]}.#{params[:format]}"}
    get '/images/:name', to: redirect {|params, req| "/assets/#{params[:name]}.#{params[:format]}"}
    get '/stylesheets/:name', to: redirect {|params, req| "/css/#{params[:name]}.#{params[:format]}"}
    get '/javascripts/:name', to: redirect {|params, req| "/js/#{params[:name]}.#{params[:format]}"}

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/calculate.rb
class Calculate < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :salutation
  
  def fullName
    fullName = firstName + " " + lastName
  end
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :customer
end

app/models/partner.rb
class Partner < ActiveRecord::Base
end

app/models/salutation.rb
class Salutation < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/window.rb
class Window < ActiveRecord::Base
  belongs_to :manufacturer
  belongs_to :materials
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render action: 'show', status: :created, location: @material }
      else
        format.html { render action: 'new' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:materialName, :energyProperty)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/calculate_helper.rb
module CalculateHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/windows_helper.rb
module WindowsHelper
end

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :materialName %><br>
    <%= f.text_field :materialName %>
  </div>
  <div class="field">
    <%= f.label :energyProperty %><br>
    <%= f.text_field :energyProperty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<h1>Listing materials</h1>

<table>
  <thead>
    <tr>
      <th>Materialname</th>
      <th>Energyproperty</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.materialName %></td>
        <td><%= material.energyProperty %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Materialname:</strong>
  <%= @material.materialName %>
</p>

<p>
  <strong>Energyproperty:</strong>
  <%= @material.energyProperty %>
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>